language: go

go:
   - 1.5
   - 1.6
   - tip

env:
   - GO15VENDOREXPERIMENT=1

install:
   - go get github.com/Masterminds/glide
   - go install github.com/Masterminds/glide 
   - go get github.com/jteeuwen/go-bindata/...
   - go get github.com/vektra/mockery/.../
   - glide install

before_script:
   - cp -R vendor/ $GOPATH/src/
   - ls $GOPATH/src/github.com/
   - go generate $(glide nv)

script:
   - pwd
   - echo $GOPATH
   - ls -lh routes
   - ls -lh vendor/github.com/jmoiron
   - mockery -dir ./routes/ -recursive -all -inpkg
   - go build -v
   - go test -v $(glide nv)
