language: go

go:
   - 1.5
   - 1.6
   - tip

env:
   - GO15VENDOREXPERIMENT=1

before_install:
   - go get github.com/Masterminds/glide
   - go install github.com/Masterminds/glide 

install:
   - go get github.com/jteeuwen/go-bindata/...
   - go get github.com/vektra/mockery/.../
   - glide install

script:
   - go build -v
   - go test -v $(glide nv)
